apiVersion: batch/v1
kind: Job
metadata:
  name: load-assets
  namespace: workout-motivator
spec:
  template:
    spec:
      containers:
      - name: load-assets
        image: workoutmotivatoracr.azurecr.io/workout-motivator-backend:latest
        command: ["python", "-c", "from app.load_assets import init_assets; init_assets()"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
      restartPolicy: Never
  backoffLimit: 4
